n1=int(input("Enter First Number :"))
n2=int(input("Enter second Number :"))
print("Addition of 2 Numbers:",(n1+n2))
print("Substraction of 2 Numbers:",(n1-n2))
print("Multiplication of 2 Numbers:",(n1*n2))
print("Division of 2 Numbers:",(n1/n2))
